POST https://heiy91n3th.execute-api.eu-central-1.amazonaws.com/state
Content-Type: application/json
Accept: application/json

{
"payload": "test"
}

###

POST https://slack.com/api/views.open
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: Bearer {{slacktoken}}

{
  "trigger_id": 123123123
}