// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MembershipRepository is an autogenerated mock type for the MembershipRepository type
type MembershipRepository struct {
	mock.Mock
}

// Subscribe provides a mock function with given fields: userId
func (_m *MembershipRepository) Subscribe(userId string) error {
	ret := _m.Called(userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
